### ISSUE TITLE
POST request is not working

### ISSUE THREAD

**Issue by pandany** [CalderaWP/calderawp-api#2]
I am making POST calls and I am getting 404 page not found error. but when I am making to a GET everything work fine, any idea?

**Comment by Shelob9** [comment]
This is the source for the API we use to server product data for a few places -- Extend tab in Caldera Forms, and our license manager v2. There are now POST requests supported.

Are you looking for help with Caldera Forms? If so, please open a ticket at https://CalderaWP.com

**Comment by pandany** [comment]
I am using v2 , but I am getting error 404 ,  are you suggesting that  I should  install Calera forms as well?

**Comment by pandany** [comment]
I got working thank you for you help.
the issue is that the webserver by default is set to take GET calls, so i hard code the POST in the boot and works like a charm now. thanks
